### ISSUE TITLE
Coding and contribution guidelines

### ISSUE THREAD

**Issue by patricknelson** [makeup/makeup-js#158]
Would love really quick to have some quick guidelines documented explaining various things, like:

* Coding style guide (e.g. Airbnb? use prettier? etc)
* If/when to submit a pull request vs. an issue or both. e.g. Some projects require all PR's to be associated with an issue (in case PR is closed), some do not. This _may not matter_ yet for this project.
* Commit message guidelines; are there any? Should they exist? e.g. Always suffix/prefix with issue number? 
* Pull request commits: To squash or not to squash?

And potentially anything else I may have missed (this was just off the top of the head).

Edit: Can potentially roll these things into https://github.com/makeup/makeup-js/blob/master/CONTRIBUTING.md

**Comment by ianmcburnie** [comment]
Yep, this is a must. Thank you for raising it.

For a long time makeup was mostly a one man show, it's only fairly recently we've had additional collaborators. For the most part I can pull over the guidelines from skin and coreui. I'd like to keep it consistent with how we operate there.

**Comment by ianmcburnie** [comment]
I made some quick additions to cover the main points above. I will be refining as I go...

**Comment by patricknelson** [comment]
> Squash any non-atomic local commits (e.g. any "work in progress" type commits) before pushing up your PR

#156 was a good example where this didn't apply IMHO. Correct?

> Please manually follow [commitlint](https://commitlint.js.org/) format for commit messages. We shall be integrating this tool soon for automatic linting of commit messages.

I've never heard of that before (always something to learn). But clicking that took me to a tool where it wasn't immediately clear what the commit message syntax should be. Is there a more direct link with instructions on what the message format should be? My 2min dive into their reference was a rabbit hole of unrelated configuration when the goal here is simply understanding what's desired for _this_ project. Ideally it's just a simple set of guidelines so you don't get bogged down and then more details can be found by going into the tool itself maybe?

**Comment by ianmcburnie** [comment]
Oops, yes bad link. I will fix it as part of https://github.com/makeup/makeup-js/issues/161

**Comment by patricknelson** [comment]
Ok cool 😅 just for my future reference, where should it be linking to?

**Comment by ianmcburnie** [comment]
I should have just copied this: https://github.com/eBay/skin/blob/master/CONTRIBUTING.md#commit-message-format
