### ISSUE TITLE
makeup-expander: ReferenceError: event is not defined

### ISSUE THREAD

**Issue by dkallus** [makeup/makeup-js#3]
I'm running into `ReferenceError: event is not defined` error when I'm running my tests.

<img width="752" alt="ref_error" src="https://user-images.githubusercontent.com/844822/82104629-85c50d80-96cc-11ea-9890-a5b07bdc8b86.png">

The following code appears to be the problem. After adding `event` parameter, my tests started passing and my page is still working fine.
https://github.com/makeup/makeup-js/blob/7a4df734d4f04803efe0c40e7a8a29c696d4ebb7/packages/makeup-expander/index.js#L83-L87

It looks like the same problem also exists here, but I didn't encounter this issue:
https://github.com/makeup/makeup-js/blob/7a4df734d4f04803efe0c40e7a8a29c696d4ebb7/packages/makeup-expander/index.js#L97-L105

**Comment by ianmcburnie** [comment]
Good catch. Will fix and publish a patch.

**Comment by dkallus** [comment]
I no longer see this issue with the patch v0.8.7. Thank you @ianmcburnie :)
