### ISSUE TITLE
Support ES6 Modules

### ISSUE THREAD

**Issue by austingardner** [makeup/makeup-js#35]
With the deprecation of IE11, it is now time to move the makeup-js repo over to ES6 modules.

**Comment by ianmcburnie** [comment]
We can probably divide this work in two, and both work from the same branch. We can tackle https://github.com/makeup/makeup-js/issues/33 at the same time.

**Comment by austingardner** [comment]
Okay sounds good to me! Which modules do you want?

**Comment by ianmcburnie** [comment]
https://twitter.com/Rich_Harris/status/1361819156648189954

**Comment by ianmcburnie** [comment]
This is blocked until we figure out how to support Lasso as well.

**Comment by ianmcburnie** [comment]
Unblocked via the `exports` field in package.json: https://antfu.me/posts/publish-esm-and-cjs
